[package]
name = "mws5"
version = "0.4.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
caches = "0.3"
serde = "1.0"
serde_json = "1.0"

[dependencies.clap]
version = "4.5"
features = ["derive"]

[profile.release]
debug = true
opt-level = 3
codegen-units = 1
lto = "fat"
